# Generated by Django 4.0.3 on 2022-04-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_rename_user_profile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
