# Generated by Django 4.0.3 on 2022-05-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_reminder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='random_string',
            field=models.CharField(default='', max_length=200),
        ),
    ]
